### ISSUE TITLE
dump of mali-fbdev on Odroid-U3

### ISSUE THREAD

**Issue by mihailescu2m** [tobiasjakobi/mali-fbdev-ioctl#1]
open called (pathname = /dev/fb0) = 4
	unknown ioctl (0x80084621) called
	close called on fbdev fd = 0
	open called (pathname = /dev/fb0) = 4
	FBIOGET_VSCREENINFO called
	xres = 1280, yres = 1024
	xres_virt = 1280, yres_virt = 3072
	xoffset = 0, yoffset = 0
	bpp = 32, grayscale = 0
	red: offset = 16, length = 8, msb_right = 0
	green: offset = 8, length = 8, msb_right = 0
	blue: offset = 0, length = 8, msb_right = 0
	transp: offset = 0, length = 0, msb_right = 0
	nonstd = 0, activate = 0
	height = 4294967295, width = 4294967295
	aflags = 1
	pixclock = 0, lmargin = 0, rmargin = 0
	umargin = 0, lmargin = 0
	hslen = 0, vslen = 0, sync = 0
	vmode = 0, rotate = 0, cspace = 0
	res = {0, 0, 0, 0}
	FBIOGET_VSCREENINFO called
	xres = 1280, yres = 1024
	xres_virt = 1280, yres_virt = 3072
	xoffset = 0, yoffset = 0
	bpp = 32, grayscale = 0
	red: offset = 16, length = 8, msb_right = 0
	green: offset = 8, length = 8, msb_right = 0
	blue: offset = 0, length = 8, msb_right = 0
	transp: offset = 0, length = 0, msb_right = 0
	nonstd = 0, activate = 0
	height = 4294967295, width = 4294967295
	aflags = 1
	pixclock = 0, lmargin = 0, rmargin = 0
	umargin = 0, lmargin = 0
	hslen = 0, vslen = 0, sync = 0
	vmode = 0, rotate = 0, cspace = 0
	res = {0, 0, 0, 0}
	FBIOGET_FSCREENINFO called
	id = 
	smem_start = 1737490432, smem_len = 47185920
	type = 0, type_aux = 0
	visual = 2, xpstep = 1, ypstep = 1
	ywstep = 0, llength = 5120
	mmio_start = 0, mmio_len = 0
	accel = 0, caps = 0
	res = {0, 0}
	info: configuration number = 1

**Comment by tobiasjakobi** [comment]
Thanks for the dump!

**Comment by tobiasjakobi** [comment]
Would you mind creating another dump? In addition to the libMali path changes, you might want to change your framebuffer dimensions here:
https://github.com/tobiasjakobi/mali-fbdev-ioctl/blob/master/test.c#L178

Thanks!

**Comment by tobiasjakobi** [comment]
And closing again. Figured out what the blob is doing.
